### ISSUE TITLE
Where is the stat file after integrating vans to gem5?

### ISSUE THREAD

**Issue by Taya666** [TheNetAdmin/VANS#7]
Hi,
I integrated vans to gem5.
But I can't find the stat file after running gem5 with vans.
How could I enable stat dump?

**Comment by TheNetAdmin** [comment]
The stats should be output to a file named `stat_dump` which is located under the dir `vans_dump` (under trace mode). Under gem5, this dir should be configured to `vans_gem5_lo_mem_dump` and `vans_gem5_hi_mem_dump`, as shown here:

https://github.com/TheNetAdmin/VANS/blob/bd58612e777e6465f7a27e732754e7908d9b2ca0/config/gem5_lo_memory.cfg#L79

https://github.com/TheNetAdmin/VANS/blob/bd58612e777e6465f7a27e732754e7908d9b2ca0/config/gem5_hi_memory.cfg#L118

The stat file output code is here:
https://github.com/TheNetAdmin/VANS/blob/f312f31205cda7c26453d694d9c29cd9dafd0156/src/general/factory.cpp#L49

and here:
https://github.com/TheNetAdmin/VANS/blob/f312f31205cda7c26453d694d9c29cd9dafd0156/src/general/utils.h#L133-L138

To enable the stat dump, modify the config file, set: 
```cfg
[dump]
type: file
```

An example is here:
https://github.com/TheNetAdmin/VANS/blob/bd58612e777e6465f7a27e732754e7908d9b2ca0/config/vans.cfg#L164-L167

It's been a while since the last time I used VANS with gem5 so I may not remember all the details. Let me know if it doesn't work.

**Comment by Taya666** [comment]
Thanks, it works
